networks:
  default:
    driver: bridge
    name:  roboshop
    # external: true #Icreated network already using docker network create roboshop
services:
  mongodb:
    image: eswarteja123/mongodb:v1
    container_name: mongodb
  catalogue:
    image: eswarteja123/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis:7.0
    container_name: redis
  user:
    image: eswarteja123/user:v1
    container_name: user
    depends_on:
    - redis
    - mongodb
  cart:
    image: eswarteja123/cart:v1
    container_name: cart
    depends_on:
    - catalogue
    - redis
  mysql:
    image: eswarteja123/mysql:v1
    container_name: mysql
  shipping:
    image: eswarteja123/shipping:v1
    container_name: shipping
    depends_on:
    - mysql
    - cart